server {
    listen       80;
    listen  [::]:80;
    server_name  itsnot.fun www.itsnot.fun;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;
# 缺失允许凭据的配置（若请求需要cookies/认证）
add_header 'Access-Control-Allow-Credentials' 'true';  # 需配合指定域名使用

# 缺失暴露自定义响应头
add_header 'Access-Control-Expose-Headers' 'Content-Length, X-Custom-Header';
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

}

server {
    listen 443 ssl;
    server_name itsnot.fun www.itsnot.fun;

    ssl_certificate /etc/nginx/conf.d/itsnot.fun.pem;
    ssl_certificate_key /etc/nginx/conf.d/itsnot.fun.key;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
# 缺失允许凭据的配置（若请求需要cookies/认证）
add_header 'Access-Control-Allow-Credentials' 'true';  # 需配合指定域名使用

# 缺失暴露自定义响应头
add_header 'Access-Control-Expose-Headers' 'Content-Length, X-Custom-Header';

    root /var/www/html;
    index index.html index.htm;

    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ =404;
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }
    }
}
