[Interface]
PrivateKey = 6KPeV86s5aGg9wL9+ERRW0vo+cSmiYXe3MYLI2lhxEw=
Address = 10.0.0.1/24
ListenPort = 33434
# 启用 IP 转发和 NAT
PostUp = sysctl -w net.ipv4.ip_forward=1; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
# PostDown = sysctl -w net.ipv4.ip_forward=0; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
Publickey = tMXpOiR6rsUkWxGrvFcdSGczXV5eOEdq60jg7sDv+QQ=
AllowedIps = 10.0.0.2/32
[Peer]
Publickey = RebgkJXKu/OB4tmQprYXU7fPFOWq1j2Eglh60XKq0xc=
AllowedIps = 10.0.0.3/32
[Peer]
PublicKey = 2Qgr14xs53rciE1ZsfLCyjGK6cf12dSBiClK4iL4Ujo=
AllowedIPs = 10.0.0.4/32
Endpoint = 101.35.164.225:51820
PersistentKeepalive = 25

PublicKey = AdIjMq9cPgrJjGqKMCaZjIKLsjxY0d1qwVhBOpnpCQI=
AllowedIPs = 10.0.0.5/32
PersistentKeepalive = 25

[Peer]
PublicKey = YHcveRPadZMYJtdlNj++y8XS6+WSljJWw9uFfqxT6TA=
AllowedIPs = 10.0.0.6/32
Endpoint = 47.100.180.176:51820
PersistentKeepalive = 25

